# Use postgres/example user/password credentials
# https://hub.docker.com/_/postgres/
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: spock
      POSTGRES_USER: spock
      POSTGRES_PASSWORD: spock
      # PGDATA:
      # POSTGRES_INITDB_ARGS:
      # POSTGRES_INITDB_WALDIR:
    ports:
      - 5432:5432
    # ports: ["5555:5432"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
